services:
  web:
    build:
      context: .
      dockerfile: ./docker/production/Dockerfile
    restart: unless-stopped
    networks:
      - laravel-production
    ports:
      - "127.0.0.1:${NGINX_PORT:-80}:80"
    depends_on:
      php-fpm:
        condition: service_healthy

  php-fpm:
    build:
      context: .
      dockerfile: ./docker/common/Dockerfile
      target: production
    restart: unless-stopped
    volumes:
      # Only mount .env file - everything else is baked into the image
      - ./.env:/var/www/.env
      - ./docker/production/entrypoint.sh:/usr/local/bin/entrypoint.sh:ro
    env_file:
      - .env
    networks:
      - laravel-production
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    command: ["php-fpm"]
    healthcheck:
      test: ["CMD-SHELL", "pidof php-fpm"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    restart: unless-stopped
    ports:
      - "127.0.0.1:${POSTGRES_PORT:-5432}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE:-app}
      - POSTGRES_USER=${POSTGRES_USERNAME:-laravel}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-secret}
    volumes:
      - postgres-data-production:/var/lib/postgresql/data
    networks:
      - laravel-production
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USERNAME:-laravel} -d ${POSTGRES_DATABASE:-app}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    restart: unless-stopped 
    networks:
      - laravel-production
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  laravel-production:

volumes:
  postgres-data-production:
  laravel-public-assets: